# -*- coding: utf-8 -*-
"""Copy of CoverLetterGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12t9PLLurd-kekgYk5ez0WebuQOcwpJh0
"""

!pip install python-docx

!apt-get install -y libreoffice

!pip install docx2pdf

!pip install datetime

def chat_with_gpt(prompt, apiKey):
    endpoint = 'https://api.openai.com/v1/chat/completions'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {apiKey}'
    }
    data = {
        'model': 'gpt-3.5-turbo',
        'prompt': prompt,
        'max_tokens': 50,
        'temperature': 0.7,
        'n': 1,
        'stop': None
    }

    print("Request data:", data)

    response = requests.post(endpoint, headers=headers, json=data)
    response_data = response.json()

    if 'choices' in response_data and len(response_data['choices']) > 0:
        return response_data['choices'][0]['text']
    else:
        print("Error in API response:", response_data)
        return None

from docx import Document
from docx2pdf import convert
from datetime import date
from google.colab import files
import subprocess
import requests

def fill_cover_letter_template(company):
    # Load the cover letter template

    # uploaded = files.upload()
    doc = Document('cover_letter_template2.docx')
    apiKey = "YOUR API KEY"


    # Example usage
    prompt = "In the first person, from the perspective of a software engineer, write 50 words about what aspects of this role interest you based on the following job description: " +  input("Paste the Job Description: ")
    response = chat_with_gpt(prompt, apiKey)
    print(response)

    # Find and replace placeholders in the template
    for paragraph in doc.paragraphs:
        if '[Company]' in paragraph.text:
            paragraph.text = paragraph.text.replace('[Company]', company)
        if '[Company Details]' in paragraph.text:
            paragraph.text = paragraph.text.replace('[Company Details]', response)

    # Save the filled cover letter as a DOCX
    doc.save('filled_cover_letter.docx')
    print("Filled cover letter saved as 'filled_cover_letter.docx'.")

    # Convert the DOCX to PDF using LibreOffice (requires installation)
    subprocess.run(['libreoffice', '--headless', '--convert-to', 'pdf', 'filled_cover_letter.docx'])
    print("Filled cover letter saved as 'filled_cover_letter.pdf'.")


# Example usage
company = input("Enter the company name: ")

fill_cover_letter_template(company)

""